using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "TagSO", menuName = "SO/Tag")]
public class TagSO : ScriptableObject
{
    public string
        _playAgain,
        _reviewBoard,
        _backToMenu,
        _giveATips,
        _parameter,
        _mode,
        _play,
        _crédit,
        _quit,
        _editorPlayer,
        _editorWinCondition,
        _editorWall,
        _editorSemiWall,
        _editorMapType,
        _editorPlay,
        _editorErase,
        _editorSave,
        _editorClean,
        _menuPlayMode,
        _menuEditorMode,
        _menuPastCode,
        _menuHelp,
        _menuCredit,
        _menuSupport,
        _menuPlayModeLeftLevel,
        _menuPlayModeRightLevel,
        _menuParameter,
        _menuPlay,
        _gameWallCollision,
        _gameWinCondition,
        _menuResetMap,
        _gameDie,
        _gameInertieBoost,
        _gameStar,
        _editorBloobWall,
        _editorBloob,
        _editorSpike,
        _editorProjectile,
        _editorInertieBoost,
        _editorStar,
        _gameBlackHole,
        _editorBlackHole,
        _editorBackToMenu,
        _menuInsta,
        _menuFiverr,
        _menuLangage,
        _menuCloseHelpWindow,
        _menuLangageSelectionCase,
        _quitParamter;
}
